# Generated by Django 4.1.6 on 2023-03-14 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_user_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user_wishlist",
            new_name="users_wishlist",
        ),
    ]
